language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows

branches:
  except:
    - staging.tmp

script:
  - cargo check
  - cargo test
  - cargo test --all-features
  - cargo test --features=m3d/obj
